astronautlevel2/Anemone3DS

- README.md
- include/fs.h
- include/themes.h
- include/unicode.h
- source/fs.c
- source/main.c
- source/themes.c
- source/unicode.c
> Add LICENSE header, update README

- include/common.h
- include/themes.h
- include/unicode.h
- source/draw.c
- source/main.c
- source/minizip/ioapi.c
- source/minizip/ioapi_mem.c
- source/minizip/unzip.c
- source/themes.c
- source/unicode.c
Causes a noticeable freeze when changing selected theme, but I think it's a reasonable price to pay for not crashing
> adds dynamic preview loading and silence minizip warnings

- source/main.c
Pressing Start from the app now sends the user to the Power Off screen. EDIT: the program now executes the correct exit method dependant on whether *hax or Rosalina is being used.
> Start button functionality

- include/splashes.h
- source/draw.c
- source/main.c
- source/splashes.c
Adds splash_delete method and calls it when button X is pressed in splashmode
> Adding splash deletion feature

- source/main.c
Not too fast yet not too slow either.
> Implement fast scroll using circle pad.

- include/draw.h
- source/draw.c
- source/main.c
- source/themes.c
Issue #35 asks for a progress bar on installation; @astronautlevel2 and I decided that it was impractical. However, the second request [a counter for how many shuffle themes are selected] was implemented quite easily.
> Resolving #35 as best as possible

- source/main.c
- source/themes.c
Astro, will this work to resolve the second point from issue #39? ~~also ignore the commit title, it was a mistake~~
> issue #39 for review

- source/main.c
Resolves point 3 of the latest request on issue thread #14.
> Fast paging [issue #14]

- Makefile
- source/draw.c
Build environment now requires Git on PATH [next commit will make this clear].
> Resolves #22

- source/fs.c
- source/splashes.c
- source/themes.c
> Minor clean up and consistency bits.

- include/loading.h
- include/themes.h
- source/loading.c
- source/main.c
- source/themes.c
only tested basic theme installing and shuffle, nobgm/bgm-only should work as well.
> Less magic numbers, and centralized theme install function.

- Makefile
- source/draw.c
- source/main.c
disables the 2 disruptive parts
> make rule for simpler citra testing

- include/draw.h
- include/instructions.h
- source/draw.c
- source/main.c
Might need fine-tuning for the position of the info line, I changed it back to an older one.
screenshots:
https://cdn.discordapp.com/attachments/366999300594728960/389222516604010497/unknown.png
https://cdn.discordapp.com/attachments/366999300594728960/389222693482004480/unknown.png
QR code to cia for testing (0bbccb6):
> General instructions-drawing function

- include/colors.h
- include/draw.h
- include/instructions.h
- source/draw.c
- source/main.c
> Ask for confirmation before deletion from SD

- source/loading.c
waiting for coggrinder to confirm if that fixed it (#102)
> fix previews logic again

- include/loading.h
- source/loading.c
- source/main.c
Works pretty well, I havent had problems with it while testing. 
QR code to cia:
> Other scrolling method - fix hack

- source/draw.c
- source/main.c
- source/themes.c
Will merge once confirmed working
> fix shuffle brick (#134)

- include/instructions.h
- source/main.c
L is now the sorting menu
R is unused
> implement L and R as extra menus instead of extra keys for X

- include/draw.h
- include/remote.h
- source/camera.c
- source/draw.c
- source/loading.c
- source/remote.c
- when loading icons
- when downloading via QR
- when loading list in the browser
- when loading preview/BGM in the browser
- when downloading from the browser
> add a loading bar

- source/pp2d/pp2d/pp2d.c
- source/remote.c
Just a placeholder until C2D arrives, whenever that is supposed to be.
> Remove deprecated C3D functions.

- include/draw.h
- source/draw.c
Also exposed `draw_text` and `draw_text_wrap` via `draw.h`.
> Added scaled text wrap

- source/draw.c
3dsx and cia builds working on O3DS 11.11.0-43E
> Very minor fix for libctru 1.6.0 compatibility

- source/themes.c
fixes #268
my bad, should have tested actually installing
> fix dumping official body and bgm, and double free

- include/fs.h
> Fixed FS error on downloading themes with * in name

- source/fs.c
- source/themes.c
Those small edits allows anemone to be usable with [This Korean Homemenu patch](https://github.com/ZeroSkill1/CTR-Hacking/tree/master/General-Hacking/Korean%20HOME%20Menu%20Theme%20Patch).
Edited the code on github directly so there's no issues about endlines.
> Korean support

- source/ui_strings.c
This PR adds French translated Strings.
I didn't test all of them but the ones we see the most are and fit correctly.
There's no modifications needed to see them, just set the console language to french, I added the French language in the switch so it works 👍
> Added French translation

- source/ui_strings.c
Adds portuguese translated strings (Brazilian portuguese)
> Added Portuguese translation

- source/ui_strings.c
Didn't notice these while testing, sorry!
> Small fixes on Portuguese 

- include/ui_strings.h
- source/remote.c
- source/ui_strings.c
> More French translations + Themes,Splashs,Badges cycling on TP using L&R

- source/ui_strings.c
Pushing this already because i don't wanna redo it for the 4th time 😋
- Translated untranslated strings
- Fixed & shortened a few strings
> Updated portuguese translation 

- source/badges.c
- source/themes.c
- source/ui_strings.c
This PR adds the following:
- Translated latest strings to french,
- Fixed a french translation,
- Added Korean translation placeholder so we can read the text correctly with their huge font,
- Added a message about Korean Homemenu Patch.
> French translation + Korean translation placeholder
